Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "AccelProfile" "adaptive"
    Option "AccelSpeed" "0.2"
    Option "ClickMethod" "clickfinger"
EndSection
